#!/usr/bin/env python3
"""Extract compact summaries from daily reports for macro-trend agent.

For each data/daily/*.md, extract:
- Front-matter (date, surprise_count, regime_signal, key_takeaway)
- Section "## Tóm tắt" (first 3-4 sentences)
- Section "## Conviction calls" or "## Conviction calls UPDATE" (table only)

Writes data/daily_summaries.md — compact (~600 tokens/day instead of ~3500).
LLM (macro-trend, macro-analyst) reads this for trend context instead of all
full report bodies. Saves ~75% tokens on monthly run while preserving:
- Regime evolution arc
- Sector conviction changes
- Surprise count + key takeaway

Usage:
  python scripts/summarize_reports.py
  python scripts/summarize_reports.py --month 2026-05   # filter to one month
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DAILY_DIR = ROOT / "data" / "daily"
OUT = ROOT / "data" / "daily_summaries.md"


def extract_front_matter(text: str) -> tuple[dict, str]:
    """Returns (front_matter_dict, body_after_fm)."""
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
    if not m:
        return {}, text
    block = m.group(1)
    body = m.group(2)
    fm = {}
    current_key = None
    for line in block.splitlines():
        if ":" in line and not line.startswith(" "):
            k, _, v = line.partition(":")
            current_key = k.strip()
            fm[current_key] = v.strip().strip("\"'")
        elif current_key and line.startswith(" "):
            # Continuation line (multi-line YAML value)
            fm[current_key] += " " + line.strip()
    return fm, body


def extract_section(body: str, heading_patterns: list[str], max_lines: int = 20) -> str:
    """Extract content of the FIRST matching section heading.

    Returns up to max_lines of content (after the heading), stopping at next heading.
    """
    lines = body.splitlines()
    in_section = False
    out = []
    count = 0
    for line in lines:
        if in_section:
            if line.startswith("## ") or line.startswith("# "):
                break
            out.append(line)
            count += 1
            if count >= max_lines:
                break
        else:
            stripped = line.strip().lower()
            if not (line.startswith("## ") or line.startswith("# ")):
                continue
            for pat in heading_patterns:
                if pat.lower() in stripped:
                    in_section = True
                    break
    # Trim trailing empty lines
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out).strip()


def summarize_one(path: Path) -> str:
    text = path.read_text()
    fm, body = extract_front_matter(text)

    date_str = fm.get("date") or path.stem
    regime = fm.get("regime_signal", "—")
    takeaway = fm.get("key_takeaway", "")
    sc = fm.get("surprise_count", "0")

    # Extract concise sections
    summary = extract_section(body, ["tóm tắt"], max_lines=10)
    conviction = extract_section(body, ["conviction", "sector positioning"], max_lines=25)

    parts = [
        f"## {date_str} — regime: `{regime}` · surprises: {sc}",
        "",
        f"**Key takeaway:** {takeaway}",
    ]
    if summary:
        parts.extend(["", "**Tóm tắt:**", summary])
    if conviction:
        parts.extend(["", "**Conviction:**", conviction])
    parts.append("")
    parts.append("---")
    parts.append("")

    return "\n".join(parts)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--month", help="Filter to YYYY-MM (default: all)")
    p.add_argument("--out", help="Output path (default: data/daily_summaries.md)")
    args = p.parse_args()

    files = sorted(DAILY_DIR.glob("*.md"))
    if args.month:
        files = [f for f in files if f.stem.startswith(args.month)]
    if not files:
        print("No daily reports found.", file=sys.stderr)
        return 1

    pieces = [
        f"# Daily summaries — {len(files)} reports",
        f"_(auto-generated by summarize_reports.py)_",
        "",
        "Each entry below contains front-matter + Tóm tắt + Conviction sections only.",
        "Read this file FIRST to navigate. For deeper context on key turning points,",
        "open the full markdown at `data/daily/<date>.md`.",
        "",
        "---",
        "",
    ]
    for f in files:
        try:
            pieces.append(summarize_one(f))
        except Exception as exc:
            print(f"  failed {f.name}: {exc}", file=sys.stderr)

    out_path = Path(args.out) if args.out else OUT
    out_path.parent.mkdir(parents=True, exist_ok=True)
    full_text = "\n".join(pieces)
    out_path.write_text(full_text)

    # Stats
    char_count = len(full_text)
    token_estimate = char_count // 4
    print(f"Wrote {out_path}")
    print(f"  {len(files)} reports → {char_count} chars (~{token_estimate} tokens)")
    print(f"  vs raw {sum(f.stat().st_size for f in files)} bytes "
          f"(~{sum(f.stat().st_size for f in files) // 4} tokens) full")
    return 0


if __name__ == "__main__":
    sys.exit(main())
